version: '3.8'

services:
  # Development service with hot-reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables better hot-reload on some systems
      - VITE_POD_NAME=local-dev-pod
      - VITE_POD_NAMESPACE=default
      - VITE_POD_IP=127.0.0.1
      - VITE_NODE_NAME=local-node
    restart: unless-stopped

  # Production service
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped 