apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    app: portfolio
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
      env: prod
  template:
    metadata:
      labels:
        app: portfolio
        env: prod
    spec:
      containers:
        - name: portfolio
          image: jjoek/portfolio:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "name"
                fieldRef:
                  fieldPath: metadata.name
              - path: "namespace"
                fieldRef:
                  fieldPath: metadata.namespace
