apiVersion: v1
kind: Service
metadata:
  name: portfolio
  labels:
    app: portfolio
    env: prod
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: portfolio
    env: prod 